/**
 * Chart of Account The Hita Hospitality Group.
 *
 * Disusun dari COA asli GuestPro — hasil penggabungan dua berkas:
 * "COA TH Uluwatu dan IGYT" dan "COA TH Legian, Sri Krisna dan Play Laundry".
 *
 * Penomoran mengikuti berkas Legian/Sri Krisna (4 digit kelompok + 2 digit rincian)
 * karena paling terstruktur. Akhiran cabang -10 / -30 serta awalan "TH -", "SK -",
 * "IGYT -" dibuang: 376 baris akun di GuestPro menyusut menjadi 181 akun yang
 * benar-benar berbeda, karena pemisahan cabang kini ditangani kolom unit pada
 * setiap baris jurnal, bukan dengan menggandakan nomor akun.
 *
 * Padanan nomor lama ke nomor baru ada di docs/pemetaan-coa-guestpro.md.
 */

export type CoaSeed = {
  code: string;
  name: string;
  type: 'ASSET' | 'LIABILITY' | 'EQUITY' | 'REVENUE' | 'COGS' | 'EXPENSE';
  subtype?: string;
  isHeader?: boolean;
  isCash?: boolean;
  cashflow?: 'OPERATING' | 'INVESTING' | 'FINANCING';
  parent?: string;
  description?: string;
};

export const COA_TEMPLATE: CoaSeed[] = [
  { code: '1.0.00', name: 'ASET', type: 'ASSET', isHeader: true },
  { code: '1100', name: 'Current Assets', type: 'ASSET', isHeader: true, parent: '1.0.00' },
  { code: '1110', name: 'Cash', type: 'ASSET', subtype: 'CASH_BANK', isHeader: true, parent: '1100' },
  { code: '1110.01', name: 'Kas Pemasukan', type: 'ASSET', subtype: 'CASH_BANK', isCash: true, cashflow: 'OPERATING', parent: '1110', description: 'Kas hasil penjualan harian sebelum disetor ke bank.' },
  { code: '1110.02', name: 'Petty Cash FO', type: 'ASSET', subtype: 'CASH_BANK', isCash: true, cashflow: 'OPERATING', parent: '1110' },
  { code: '1110.03', name: 'Petty Cash Purchasing', type: 'ASSET', subtype: 'CASH_BANK', isCash: true, cashflow: 'OPERATING', parent: '1110' },
  { code: '1110.04', name: 'Petty Cash HR', type: 'ASSET', subtype: 'CASH_BANK', isCash: true, cashflow: 'OPERATING', parent: '1110' },
  { code: '1110.05', name: 'Petty Cash Laundry', type: 'ASSET', subtype: 'CASH_BANK', isCash: true, cashflow: 'OPERATING', parent: '1110' },
  { code: '1110.06', name: 'Shopee Pay', type: 'ASSET', subtype: 'CASH_BANK', isCash: true, cashflow: 'OPERATING', parent: '1110' },
  { code: '1110.07', name: 'Grab Pay', type: 'ASSET', subtype: 'CASH_BANK', isCash: true, cashflow: 'OPERATING', parent: '1110' },
  { code: '1120', name: 'Bank', type: 'ASSET', subtype: 'CASH_BANK', isHeader: true, parent: '1100' },
  { code: '1120.01', name: 'Bank Mandiri/BCA', type: 'ASSET', subtype: 'CASH_BANK', isCash: true, cashflow: 'OPERATING', parent: '1120' },
  { code: '1120.02', name: 'Bank BCA - Proyek', type: 'ASSET', subtype: 'CASH_BANK', isCash: true, cashflow: 'OPERATING', parent: '1120', description: 'Rekening khusus dana proyek.' },
  { code: '1120.03', name: 'Bank BRI', type: 'ASSET', subtype: 'CASH_BANK', isCash: true, cashflow: 'OPERATING', parent: '1120' },
  { code: '1120.04', name: 'Kas Property', type: 'ASSET', subtype: 'CASH_BANK', isCash: true, cashflow: 'OPERATING', parent: '1120' },
  { code: '1130', name: 'Piutang Usaha', type: 'ASSET', subtype: 'RECEIVABLE', isHeader: true, parent: '1100' },
  { code: '1130.01', name: 'Piutang EDC', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1130' },
  { code: '1130.02', name: 'Piutang QRIS', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1130' },
  { code: '1130.03', name: 'City Ledger', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1130' },
  { code: '1130.04', name: 'Guest Ledger', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1130' },
  { code: '1131', name: 'Piutang OTA & Travel Agent', type: 'ASSET', subtype: 'RECEIVABLE', isHeader: true, parent: '1100' },
  { code: '1131.01', name: 'Piutang - Booking.com', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1131' },
  { code: '1131.02', name: 'Piutang - Agoda Home', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1131' },
  { code: '1131.03', name: 'Piutang - Agoda YCS', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1131' },
  { code: '1131.04', name: 'Piutang - Airbnb', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1131' },
  { code: '1131.05', name: 'Piutang - Expedia', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1131' },
  { code: '1131.06', name: 'Piutang - Tiket.com', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1131' },
  { code: '1131.07', name: 'Piutang - Traveloka', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1131' },
  { code: '1131.08', name: 'Piutang - BE', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1131' },
  { code: '1131.09', name: 'Piutang - Hostel World', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1131' },
  { code: '1131.10', name: 'Piutang - Klook', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1131' },
  { code: '1131.11', name: 'Piutang - Trip.com', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1131', description: 'Pasangan dari akun Komisi Trip.com.' },
  { code: '1131.12', name: 'Piutang - Travel Agent (Korporat/Offline)', type: 'ASSET', subtype: 'RECEIVABLE', cashflow: 'OPERATING', parent: '1131' },
  { code: '1140', name: 'Persediaan Operasional', type: 'ASSET', subtype: 'INVENTORY', isHeader: true, parent: '1100' },
  { code: '1140.01', name: 'Persediaan Peralatan Kitchen', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1140' },
  { code: '1140.02', name: 'Persediaan Perlengkapan dan Peralatan Amenities', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1140' },
  { code: '1140.03', name: 'Persediaan Chemical HK', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1140' },
  { code: '1140.04', name: 'Persediaan Perlengkapan Room', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1140' },
  { code: '1140.05', name: 'Persediaan Room Supplies', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1140' },
  { code: '1140.06', name: 'Persediaan Alat dan Bahan Engineering', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1140' },
  { code: '1140.07', name: 'Persediaan Peralatan dan Perlengkapan HK', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1140' },
  { code: '1140.08', name: 'Persediaan Peralatan dan Perlengkapan Kantor', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1140' },
  { code: '1140.09', name: 'Persediaan Peralatan dan Perlengkapan FO', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1140' },
  { code: '1140.10', name: 'Persediaan Peralatan dan Perlengkapan Resto', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1140' },
  { code: '1140.11', name: 'Persediaan Packaging', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1140' },
  { code: '1141', name: 'Persediaan Linen', type: 'ASSET', subtype: 'INVENTORY', isHeader: true, parent: '1100' },
  { code: '1141.01', name: 'Persediaan Linen', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1141' },
  { code: '1142', name: 'Persediaan F&B', type: 'ASSET', subtype: 'INVENTORY', isHeader: true, parent: '1100' },
  { code: '1142.01', name: 'Persediaan Bahan Makanan', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1142' },
  { code: '1142.02', name: 'Persediaan Bahan Minuman', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1142' },
  { code: '1142.03', name: 'Persediaan Minuman (F&B)', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1142' },
  { code: '1142.04', name: 'Persediaan Minuman Alkohol', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1142' },
  { code: '1142.05', name: 'Persediaan Pastry dan Kue', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1142' },
  { code: '1142.06', name: 'Persediaan Shared F&B Inventory', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1142' },
  { code: '1143', name: 'Persediaan Utilitas & Laundry', type: 'ASSET', subtype: 'INVENTORY', isHeader: true, parent: '1100' },
  { code: '1143.01', name: 'Persediaan Tabung Gas', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1143' },
  { code: '1143.02', name: 'Persediaan Galon', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1143' },
  { code: '1143.03', name: 'Persediaan Chemical Laundry', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1143' },
  { code: '1143.04', name: 'Persediaan Plastik Laundry', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1143' },
  { code: '1143.05', name: 'Persediaan Perlengkapan dan Peralatan Laundry', type: 'ASSET', subtype: 'INVENTORY', cashflow: 'OPERATING', parent: '1143' },
  { code: '1190', name: 'Akun Antar Unit', type: 'ASSET', subtype: 'INTERUNIT', isHeader: true, parent: '1100' },
  { code: '1190.01', name: 'Piutang Antar Unit', type: 'ASSET', subtype: 'INTERUNIT', cashflow: 'OPERATING', parent: '1190', description: 'Dibuat otomatis saat satu cabang menalangi cabang lain. Saldonya harus selalu meniadakan 2190.01.' },
  { code: '1200', name: 'Non Current Assets', type: 'ASSET', subtype: 'FIXED_ASSET', isHeader: true, parent: '1.0.00' },
  { code: '1210', name: 'Fixed Asset', type: 'ASSET', subtype: 'FIXED_ASSET', isHeader: true, parent: '1200' },
  { code: '1210.01', name: 'Gedung & Bangunan', type: 'ASSET', subtype: 'FIXED_ASSET', cashflow: 'INVESTING', parent: '1210' },
  { code: '1210.02', name: 'Perabotan & Perlengkapan (FF&E)', type: 'ASSET', subtype: 'FIXED_ASSET', cashflow: 'INVESTING', parent: '1210' },
  { code: '1210.03', name: 'Akumulasi Penyusutan FF&E', type: 'ASSET', subtype: 'FIXED_ASSET', parent: '1210' },
  { code: '1220', name: 'Aset Dalam Pengerjaan', type: 'ASSET', subtype: 'FIXED_ASSET', isHeader: true, parent: '1200' },
  { code: '1220.01', name: 'Aset Dalam Pengerjaan', type: 'ASSET', subtype: 'FIXED_ASSET', cashflow: 'INVESTING', parent: '1220', description: 'Penampung biaya proyek yang belum selesai.' },
  { code: '2.0.00', name: 'KEWAJIBAN', type: 'LIABILITY', isHeader: true },
  { code: '2100', name: 'Current Liability', type: 'LIABILITY', isHeader: true, parent: '2.0.00' },
  { code: '2101', name: 'Payables', type: 'LIABILITY', subtype: 'PAYABLE', isHeader: true, parent: '2100' },
  { code: '2101.01', name: 'Account Payable', type: 'LIABILITY', subtype: 'PAYABLE', cashflow: 'OPERATING', parent: '2101' },
  { code: '2101.02', name: 'Uang Muka Tamu', type: 'LIABILITY', subtype: 'PAYABLE', cashflow: 'OPERATING', parent: '2101' },
  { code: '2101.03', name: 'Utang Bank', type: 'LIABILITY', subtype: 'LOAN', cashflow: 'FINANCING', parent: '2101' },
  { code: '2101.04', name: 'Utang Usaha', type: 'LIABILITY', subtype: 'PAYABLE', cashflow: 'OPERATING', parent: '2101' },
  { code: '2101.05', name: 'Utang Pajak', type: 'LIABILITY', subtype: 'TAX', cashflow: 'OPERATING', parent: '2101' },
  { code: '2101.06', name: 'AP Commission', type: 'LIABILITY', subtype: 'PAYABLE', cashflow: 'OPERATING', parent: '2101', description: 'Komisi OTA yang belum dibayarkan.' },
  { code: '2101.07', name: 'Utang Owner', type: 'LIABILITY', subtype: 'LOAN', cashflow: 'FINANCING', parent: '2101' },
  { code: '2102', name: 'Taxes Payable', type: 'LIABILITY', subtype: 'TAX', isHeader: true, parent: '2100' },
  { code: '2102.01', name: 'Hotel Tax / PHR', type: 'LIABILITY', subtype: 'TAX', cashflow: 'OPERATING', parent: '2102' },
  { code: '2102.02', name: 'Cafe Tax', type: 'LIABILITY', subtype: 'TAX', cashflow: 'OPERATING', parent: '2102' },
  { code: '2103', name: 'Others Payable', type: 'LIABILITY', subtype: 'PAYABLE', isHeader: true, parent: '2100' },
  { code: '2103.01', name: 'Service Charge', type: 'LIABILITY', subtype: 'PAYABLE', cashflow: 'OPERATING', parent: '2103' },
  { code: '2190', name: 'Akun Antar Unit', type: 'LIABILITY', subtype: 'INTERUNIT', isHeader: true, parent: '2100' },
  { code: '2190.01', name: 'Hutang Antar Unit', type: 'LIABILITY', subtype: 'INTERUNIT', cashflow: 'OPERATING', parent: '2190', description: 'Pasangan dari 1190.01, dibuat otomatis saat uang berpindah antar cabang.' },
  { code: '3.0.00', name: 'MODAL', type: 'EQUITY', isHeader: true },
  { code: '3100', name: 'Capital & Equity', type: 'EQUITY', isHeader: true, parent: '3.0.00' },
  { code: '3101', name: 'Capital & Equity', type: 'EQUITY', isHeader: true, parent: '3100' },
  { code: '3101.01', name: 'Modal Pemilik', type: 'EQUITY', cashflow: 'FINANCING', parent: '3101' },
  { code: '3101.02', name: 'Opening Balance Equity', type: 'EQUITY', parent: '3101', description: 'Lawan jurnal saldo awal saat migrasi dari GuestPro.' },
  { code: '3101.03', name: 'Prive', type: 'EQUITY', cashflow: 'FINANCING', parent: '3101' },
  { code: '3101.04', name: 'Laba Ditahan', type: 'EQUITY', parent: '3101' },
  { code: '3101.05', name: 'Profit this month', type: 'EQUITY', parent: '3101' },
  { code: '3101.06', name: 'Laba Tahun Berjalan', type: 'EQUITY', parent: '3101' },
  { code: '3101.07', name: 'Management Fee', type: 'EQUITY', cashflow: 'FINANCING', parent: '3101' },
  { code: '4.0.00', name: 'PENDAPATAN', type: 'REVENUE', isHeader: true },
  { code: '4100', name: 'Operating Incomes', type: 'REVENUE', isHeader: true, parent: '4.0.00' },
  { code: '4110', name: 'Pendapatan Kamar & Hotel', type: 'REVENUE', subtype: 'ROOM_REVENUE', isHeader: true, parent: '4100' },
  { code: '4110.01', name: 'Pendapatan Kamar', type: 'REVENUE', subtype: 'ROOM_REVENUE', cashflow: 'OPERATING', parent: '4110' },
  { code: '4110.02', name: 'Pendapatan Upgrade Room', type: 'REVENUE', subtype: 'ROOM_REVENUE', cashflow: 'OPERATING', parent: '4110' },
  { code: '4110.03', name: 'Pendapatan Early CI / Late CO', type: 'REVENUE', subtype: 'ROOM_REVENUE', cashflow: 'OPERATING', parent: '4110' },
  { code: '4110.04', name: 'Pendapatan Rental Motor', type: 'REVENUE', subtype: 'OTHER_REVENUE', cashflow: 'OPERATING', parent: '4110' },
  { code: '4110.05', name: 'Pendapatan Rental Mobil', type: 'REVENUE', subtype: 'OTHER_REVENUE', cashflow: 'OPERATING', parent: '4110' },
  { code: '4110.06', name: 'Pendapatan Tour & Airport Transfer', type: 'REVENUE', subtype: 'OTHER_REVENUE', cashflow: 'OPERATING', parent: '4110' },
  { code: '4110.07', name: 'Pendapatan Denda & Kerusakan', type: 'REVENUE', subtype: 'OTHER_REVENUE', cashflow: 'OPERATING', parent: '4110' },
  { code: '4110.08', name: 'Pendapatan Layanan Tamu (Honeymoon/Birthday/Dll)', type: 'REVENUE', subtype: 'OTHER_REVENUE', cashflow: 'OPERATING', parent: '4110' },
  { code: '4110.09', name: 'Pendapatan Lain-lain', type: 'REVENUE', subtype: 'OTHER_REVENUE', cashflow: 'OPERATING', parent: '4110' },
  { code: '4111', name: 'Pendapatan F&B', type: 'REVENUE', subtype: 'FNB_REVENUE', isHeader: true, parent: '4100' },
  { code: '4111.01', name: 'Pendapatan (F&B) - Makanan', type: 'REVENUE', subtype: 'FNB_REVENUE', cashflow: 'OPERATING', parent: '4111' },
  { code: '4111.02', name: 'Pendapatan (F&B) - Minuman', type: 'REVENUE', subtype: 'FNB_REVENUE', cashflow: 'OPERATING', parent: '4111' },
  { code: '4111.03', name: 'Pendapatan (F&B) - Breakfast', type: 'REVENUE', subtype: 'FNB_REVENUE', cashflow: 'OPERATING', parent: '4111' },
  { code: '4111.04', name: 'Pendapatan (F&B) Minuman FO', type: 'REVENUE', subtype: 'FNB_REVENUE', cashflow: 'OPERATING', parent: '4111' },
  { code: '4111.05', name: 'Pendapatan Online Delivery - Makanan', type: 'REVENUE', subtype: 'FNB_REVENUE', cashflow: 'OPERATING', parent: '4111' },
  { code: '4111.06', name: 'Pendapatan Online Delivery - Minuman', type: 'REVENUE', subtype: 'FNB_REVENUE', cashflow: 'OPERATING', parent: '4111' },
  { code: '4112', name: 'Pendapatan Laundry', type: 'REVENUE', subtype: 'LAUNDRY_REVENUE', isHeader: true, parent: '4100' },
  { code: '4112.01', name: 'Pendapatan Laundry Kiloan', type: 'REVENUE', subtype: 'LAUNDRY_REVENUE', cashflow: 'OPERATING', parent: '4112' },
  { code: '4112.02', name: 'Pendapatan Laundry Satuan', type: 'REVENUE', subtype: 'LAUNDRY_REVENUE', cashflow: 'OPERATING', parent: '4112' },
  { code: '4112.03', name: 'Pendapatan Standart Laundry', type: 'REVENUE', subtype: 'LAUNDRY_REVENUE', cashflow: 'OPERATING', parent: '4112', description: 'Jasa laundry untuk tamu hotel maupun hotel lain.' },
  { code: '4113', name: 'Pendapatan Lain-lain', type: 'REVENUE', subtype: 'OTHER_REVENUE', isHeader: true, parent: '4100' },
  { code: '4113.01', name: 'Pendapatan PMS - Belum Dialokasikan', type: 'REVENUE', subtype: 'OTHER_REVENUE', cashflow: 'OPERATING', parent: '4113', description: 'Penampung sementara saat impor dari PMS.' },
  { code: '4113.02', name: 'Pendapatan Bunga Bank', type: 'REVENUE', subtype: 'OTHER_REVENUE', cashflow: 'OPERATING', parent: '4113' },
  { code: '5.0.00', name: 'HARGA POKOK PENJUALAN', type: 'COGS', isHeader: true },
  { code: '5100', name: 'Cost Of Sales', type: 'COGS', isHeader: true, parent: '5.0.00' },
  { code: '5110', name: 'Cost Of Sales', type: 'COGS', isHeader: true, parent: '5100' },
  { code: '5110.01', name: 'HPP Food (F&B)', type: 'COGS', cashflow: 'OPERATING', parent: '5110' },
  { code: '5110.02', name: 'HPP Minuman (F&B)', type: 'COGS', cashflow: 'OPERATING', parent: '5110' },
  { code: '5110.03', name: 'HPP Breakfast (F&B)', type: 'COGS', cashflow: 'OPERATING', parent: '5110' },
  { code: '5110.04', name: 'HPP Complimentary / Spoilage', type: 'COGS', cashflow: 'OPERATING', parent: '5110' },
  { code: '5110.05', name: 'HPP Tour & Airport Transfer', type: 'COGS', cashflow: 'OPERATING', parent: '5110' },
  { code: '5110.06', name: 'HPP Minuman Alkohol', type: 'COGS', cashflow: 'OPERATING', parent: '5110' },
  { code: '6.0.00', name: 'BEBAN OPERASIONAL', type: 'EXPENSE', isHeader: true },
  { code: '6100', name: 'Operating Expenses', type: 'EXPENSE', isHeader: true, parent: '6.0.00' },
  { code: '6110', name: 'Komisi OTA & Travel Agent', type: 'EXPENSE', subtype: 'COMMISSION', isHeader: true, parent: '6100' },
  { code: '6110.01', name: 'Komisi - Booking.com', type: 'EXPENSE', subtype: 'COMMISSION', cashflow: 'OPERATING', parent: '6110' },
  { code: '6110.02', name: 'Biaya Layanan Booking.com', type: 'EXPENSE', subtype: 'COMMISSION', cashflow: 'OPERATING', parent: '6110' },
  { code: '6110.03', name: 'Komisi - Agoda Home', type: 'EXPENSE', subtype: 'COMMISSION', cashflow: 'OPERATING', parent: '6110' },
  { code: '6110.04', name: 'Komisi - Agoda YCS', type: 'EXPENSE', subtype: 'COMMISSION', cashflow: 'OPERATING', parent: '6110' },
  { code: '6110.05', name: 'Komisi - Airbnb', type: 'EXPENSE', subtype: 'COMMISSION', cashflow: 'OPERATING', parent: '6110' },
  { code: '6110.06', name: 'Komisi - Expedia', type: 'EXPENSE', subtype: 'COMMISSION', cashflow: 'OPERATING', parent: '6110' },
  { code: '6110.07', name: 'Komisi - Tiket.com', type: 'EXPENSE', subtype: 'COMMISSION', cashflow: 'OPERATING', parent: '6110' },
  { code: '6110.08', name: 'Komisi - Traveloka', type: 'EXPENSE', subtype: 'COMMISSION', cashflow: 'OPERATING', parent: '6110' },
  { code: '6110.09', name: 'Komisi - BE', type: 'EXPENSE', subtype: 'COMMISSION', cashflow: 'OPERATING', parent: '6110' },
  { code: '6110.10', name: 'Komisi - Hostel World', type: 'EXPENSE', subtype: 'COMMISSION', cashflow: 'OPERATING', parent: '6110' },
  { code: '6110.11', name: 'Komisi - Trip.com', type: 'EXPENSE', subtype: 'COMMISSION', cashflow: 'OPERATING', parent: '6110' },
  { code: '6110.12', name: 'Komisi - Klook', type: 'EXPENSE', subtype: 'COMMISSION', cashflow: 'OPERATING', parent: '6110' },
  { code: '6110.13', name: 'Komisi - Travel Agent (Korporat/Offline)', type: 'EXPENSE', subtype: 'COMMISSION', cashflow: 'OPERATING', parent: '6110' },
  { code: '6120', name: 'Biaya Administrasi, Utilitas & Lain-lain', type: 'EXPENSE', subtype: 'ADMIN', isHeader: true, parent: '6100' },
  { code: '6120.01', name: 'Biaya Listrik', type: 'EXPENSE', subtype: 'UTILITIES', cashflow: 'OPERATING', parent: '6120' },
  { code: '6120.02', name: 'Biaya Internet', type: 'EXPENSE', subtype: 'UTILITIES', cashflow: 'OPERATING', parent: '6120' },
  { code: '6120.03', name: 'Biaya Pajak', type: 'EXPENSE', subtype: 'TAX', cashflow: 'OPERATING', parent: '6120' },
  { code: '6120.04', name: 'Biaya Administrasi & Umum', type: 'EXPENSE', subtype: 'ADMIN', cashflow: 'OPERATING', parent: '6120' },
  { code: '6120.05', name: 'Biaya Software dan Langganan', type: 'EXPENSE', subtype: 'ADMIN', cashflow: 'OPERATING', parent: '6120', description: 'Termasuk langganan PMS.' },
  { code: '6120.06', name: 'Biaya Peralatan dan Perlengkapan Kantor', type: 'EXPENSE', subtype: 'ADMIN', cashflow: 'OPERATING', parent: '6120' },
  { code: '6120.07', name: 'Biaya Diskon Tamu', type: 'EXPENSE', subtype: 'ADMIN', cashflow: 'OPERATING', parent: '6120' },
  { code: '6120.08', name: 'Biaya Refund dan Kompensasi Tamu', type: 'EXPENSE', subtype: 'ADMIN', cashflow: 'OPERATING', parent: '6120' },
  { code: '6120.09', name: 'Biaya Lain-lain', type: 'EXPENSE', subtype: 'OTHER', cashflow: 'OPERATING', parent: '6120' },
  { code: '6130', name: 'Biaya Karyawan', type: 'EXPENSE', subtype: 'PAYROLL', isHeader: true, parent: '6100' },
  { code: '6130.01', name: 'Biaya Gaji Karyawan', type: 'EXPENSE', subtype: 'PAYROLL', cashflow: 'OPERATING', parent: '6130' },
  { code: '6130.02', name: 'Biaya Service Karyawan', type: 'EXPENSE', subtype: 'PAYROLL', cashflow: 'OPERATING', parent: '6130' },
  { code: '6130.03', name: 'Biaya THR', type: 'EXPENSE', subtype: 'PAYROLL', cashflow: 'OPERATING', parent: '6130' },
  { code: '6130.04', name: 'Biaya Bonus Management', type: 'EXPENSE', subtype: 'PAYROLL', cashflow: 'OPERATING', parent: '6130' },
  { code: '6130.05', name: 'Biaya Marketing', type: 'EXPENSE', subtype: 'MARKETING', cashflow: 'OPERATING', parent: '6130' },
  { code: '6130.06', name: 'Biaya Administrasi Bank', type: 'EXPENSE', subtype: 'ADMIN', cashflow: 'OPERATING', parent: '6130' },
  { code: '6140', name: 'Biaya Linen', type: 'EXPENSE', subtype: 'OPERATIONAL', isHeader: true, parent: '6100' },
  { code: '6140.01', name: 'Biaya Linen', type: 'EXPENSE', subtype: 'OPERATIONAL', cashflow: 'OPERATING', parent: '6140' },
  { code: '6150', name: 'Biaya Operasional', type: 'EXPENSE', subtype: 'OPERATIONAL', isHeader: true, parent: '6100' },
  { code: '6150.01', name: 'Biaya Peralatan Kitchen', type: 'EXPENSE', subtype: 'OPERATIONAL', cashflow: 'OPERATING', parent: '6150' },
  { code: '6150.02', name: 'Biaya Perlengkapan dan Peralatan Amenities', type: 'EXPENSE', subtype: 'OPERATIONAL', cashflow: 'OPERATING', parent: '6150' },
  { code: '6150.03', name: 'Biaya Chemical HK', type: 'EXPENSE', subtype: 'OPERATIONAL', cashflow: 'OPERATING', parent: '6150' },
  { code: '6150.04', name: 'Biaya Perlengkapan Room', type: 'EXPENSE', subtype: 'OPERATIONAL', cashflow: 'OPERATING', parent: '6150' },
  { code: '6150.05', name: 'Biaya Room Supplies', type: 'EXPENSE', subtype: 'OPERATIONAL', cashflow: 'OPERATING', parent: '6150' },
  { code: '6150.06', name: 'Biaya Layanan Tamu', type: 'EXPENSE', subtype: 'OPERATIONAL', cashflow: 'OPERATING', parent: '6150' },
  { code: '6150.07', name: 'Biaya Layanan Tamu FREE', type: 'EXPENSE', subtype: 'OPERATIONAL', cashflow: 'OPERATING', parent: '6150' },
  { code: '6150.08', name: 'Biaya Alat dan Bahan Engineering', type: 'EXPENSE', subtype: 'OPERATIONAL', cashflow: 'OPERATING', parent: '6150' },
  { code: '6150.09', name: 'Biaya Peralatan dan Perlengkapan HK', type: 'EXPENSE', subtype: 'OPERATIONAL', cashflow: 'OPERATING', parent: '6150' },
  { code: '6150.10', name: 'Biaya Peralatan dan Perlengkapan FO', type: 'EXPENSE', subtype: 'OPERATIONAL', cashflow: 'OPERATING', parent: '6150' },
  { code: '6150.11', name: 'Biaya Renovasi & Penambahan Fasilitas', type: 'EXPENSE', subtype: 'OPERATIONAL', cashflow: 'OPERATING', parent: '6150' },
  { code: '6150.12', name: 'Biaya Laundry', type: 'EXPENSE', subtype: 'OPERATIONAL', cashflow: 'OPERATING', parent: '6150', description: 'Jasa laundry yang dibayarkan ke pihak lain, termasuk ke Play Laundry.' },
  { code: '6150.13', name: 'Biaya Laundry Linen', type: 'EXPENSE', subtype: 'OPERATIONAL', cashflow: 'OPERATING', parent: '6150' },
  { code: '6160', name: 'Biaya Utilitas Kitchen & Gas', type: 'EXPENSE', subtype: 'UTILITIES', isHeader: true, parent: '6100' },
  { code: '6160.01', name: 'Biaya Gas HK', type: 'EXPENSE', subtype: 'UTILITIES', cashflow: 'OPERATING', parent: '6160' },
  { code: '6160.02', name: 'Biaya Gas Kitchen', type: 'EXPENSE', subtype: 'UTILITIES', cashflow: 'OPERATING', parent: '6160' },
  { code: '6160.03', name: 'Biaya Galon HK', type: 'EXPENSE', subtype: 'UTILITIES', cashflow: 'OPERATING', parent: '6160' },
  { code: '6160.04', name: 'Biaya Galon Kitchen', type: 'EXPENSE', subtype: 'UTILITIES', cashflow: 'OPERATING', parent: '6160' },
  { code: '6160.05', name: 'Biaya Air Isi Ulang', type: 'EXPENSE', subtype: 'UTILITIES', cashflow: 'OPERATING', parent: '6160' },
  { code: '6160.06', name: 'Biaya Tabung Gas', type: 'EXPENSE', subtype: 'UTILITIES', cashflow: 'OPERATING', parent: '6160' },
  { code: '6170', name: 'Biaya Laundry', type: 'EXPENSE', subtype: 'LAUNDRY', isHeader: true, parent: '6100' },
  { code: '6170.01', name: 'Biaya Sabun & Chemical Laundry', type: 'EXPENSE', subtype: 'LAUNDRY', cashflow: 'OPERATING', parent: '6170' },
  { code: '6170.02', name: 'Biaya Perlengkapan (Supplies) Laundry', type: 'EXPENSE', subtype: 'LAUNDRY', cashflow: 'OPERATING', parent: '6170' },
  { code: '6170.03', name: 'Biaya Perawatan Mesin Laundry', type: 'EXPENSE', subtype: 'LAUNDRY', cashflow: 'OPERATING', parent: '6170' },
  { code: '6170.04', name: 'Biaya BBM Laundry', type: 'EXPENSE', subtype: 'LAUNDRY', cashflow: 'OPERATING', parent: '6170' },
  { code: '6180', name: 'Biaya Pemeliharaan', type: 'EXPENSE', subtype: 'MAINTENANCE', isHeader: true, parent: '6100' },
  { code: '6180.01', name: 'Biaya Pemeliharaan Room', type: 'EXPENSE', subtype: 'MAINTENANCE', cashflow: 'OPERATING', parent: '6180' },
  { code: '6180.02', name: 'Biaya Pemeliharaan Kendaraan (Service/Samsat/dll)', type: 'EXPENSE', subtype: 'MAINTENANCE', cashflow: 'OPERATING', parent: '6180' },
  { code: '6180.03', name: 'Biaya Pemeliharaan Wifi', type: 'EXPENSE', subtype: 'MAINTENANCE', cashflow: 'OPERATING', parent: '6180' },
  { code: '6180.04', name: 'Biaya Pemeliharaan Furniture', type: 'EXPENSE', subtype: 'MAINTENANCE', cashflow: 'OPERATING', parent: '6180' },
  { code: '6180.05', name: 'Biaya Pemeliharaan Public Area', type: 'EXPENSE', subtype: 'MAINTENANCE', cashflow: 'OPERATING', parent: '6180' },
  { code: '6180.06', name: 'Biaya Pemeliharaan Office', type: 'EXPENSE', subtype: 'MAINTENANCE', cashflow: 'OPERATING', parent: '6180' },
  { code: '6180.07', name: 'Biaya Pemeliharaan AC', type: 'EXPENSE', subtype: 'MAINTENANCE', cashflow: 'OPERATING', parent: '6180' },
  { code: '6180.08', name: 'Biaya Pemeliharaan Linen', type: 'EXPENSE', subtype: 'MAINTENANCE', cashflow: 'OPERATING', parent: '6180' },
  { code: '6180.09', name: 'Biaya Pemeliharaan Peralatan Kantor', type: 'EXPENSE', subtype: 'MAINTENANCE', cashflow: 'OPERATING', parent: '6180' },
  { code: '6180.10', name: 'Biaya Pemeliharaan Alat & Mesin - Engineering', type: 'EXPENSE', subtype: 'MAINTENANCE', cashflow: 'OPERATING', parent: '6180' },
  { code: '6180.11', name: 'Biaya Pemeliharaan Kitchen', type: 'EXPENSE', subtype: 'MAINTENANCE', cashflow: 'OPERATING', parent: '6180' },
  { code: '6180.12', name: 'Biaya Pemeliharaan Kasir dan Bar', type: 'EXPENSE', subtype: 'MAINTENANCE', cashflow: 'OPERATING', parent: '6180' },
  { code: '6180.13', name: 'Biaya Pemeliharaan Bangunan dan Fasilitas', type: 'EXPENSE', subtype: 'MAINTENANCE', cashflow: 'OPERATING', parent: '6180' },
  { code: '6181', name: 'Biaya HR', type: 'EXPENSE', subtype: 'PAYROLL', isHeader: true, parent: '6100' },
  { code: '6181.01', name: 'Biaya Rekrutmen', type: 'EXPENSE', subtype: 'PAYROLL', cashflow: 'OPERATING', parent: '6181' },
  { code: '6181.02', name: 'Biaya Development Staff', type: 'EXPENSE', subtype: 'PAYROLL', cashflow: 'OPERATING', parent: '6181' },
  { code: '6181.03', name: 'Biaya Kompensasi', type: 'EXPENSE', subtype: 'PAYROLL', cashflow: 'OPERATING', parent: '6181' },
  { code: '6181.04', name: 'Biaya Konsumsi', type: 'EXPENSE', subtype: 'PAYROLL', cashflow: 'OPERATING', parent: '6181' },
  { code: '6181.05', name: 'Biaya Perlengkapan Staf', type: 'EXPENSE', subtype: 'PAYROLL', cashflow: 'OPERATING', parent: '6181' },
  { code: '6190', name: 'Biaya F&B / Cafe', type: 'EXPENSE', subtype: 'FNB', isHeader: true, parent: '6100' },
  { code: '6190.01', name: 'Biaya Bahan Makanan', type: 'EXPENSE', subtype: 'FNB', cashflow: 'OPERATING', parent: '6190' },
  { code: '6190.02', name: 'Biaya Bahan Minuman', type: 'EXPENSE', subtype: 'FNB', cashflow: 'OPERATING', parent: '6190' },
  { code: '6190.03', name: 'Biaya Perlengkapan F&B', type: 'EXPENSE', subtype: 'FNB', cashflow: 'OPERATING', parent: '6190' },
  { code: '6190.04', name: 'Biaya Packaging', type: 'EXPENSE', subtype: 'FNB', cashflow: 'OPERATING', parent: '6190' },
  { code: '6190.05', name: 'Biaya Peralatan dan Perlengkapan Resto', type: 'EXPENSE', subtype: 'FNB', cashflow: 'OPERATING', parent: '6190' },
  { code: '6190.06', name: 'Biaya Peralatan dan Perlengkapan Cafe', type: 'EXPENSE', subtype: 'FNB', cashflow: 'OPERATING', parent: '6190' },
  { code: '6190.07', name: 'Biaya Shared F&B Inventory', type: 'EXPENSE', subtype: 'FNB', cashflow: 'OPERATING', parent: '6190' },
  { code: '6190.08', name: 'Biaya Chemical & Supplies', type: 'EXPENSE', subtype: 'FNB', cashflow: 'OPERATING', parent: '6190' },
  { code: '6191', name: 'Biaya Penyusutan', type: 'EXPENSE', subtype: 'DEPRECIATION', isHeader: true, parent: '6100' },
  { code: '6191.01', name: 'Biaya Penyusutan FF&E', type: 'EXPENSE', subtype: 'DEPRECIATION', parent: '6191', description: 'Beban non-kas, tidak dihitung pada proyeksi arus kas.' },
  { code: '7.0.00', name: 'PENDAPATAN NON OPERASIONAL', type: 'REVENUE', subtype: 'NON_OPERATING', isHeader: true },
  { code: '7100', name: 'Non Operating Incomes', type: 'REVENUE', subtype: 'NON_OPERATING', isHeader: true, parent: '7.0.00' },
  { code: '7110', name: 'Other Income', type: 'REVENUE', subtype: 'NON_OPERATING', isHeader: true, parent: '7100' },
  { code: '7110.01', name: 'Interest Income', type: 'REVENUE', subtype: 'NON_OPERATING', cashflow: 'OPERATING', parent: '7110' },
  { code: '8.0.00', name: 'BEBAN NON OPERASIONAL', type: 'EXPENSE', subtype: 'NON_OPERATING', isHeader: true },
  { code: '8100', name: 'Non Operating Expenses', type: 'EXPENSE', subtype: 'NON_OPERATING', isHeader: true, parent: '8.0.00' },
  { code: '8110', name: 'Other Expenses', type: 'EXPENSE', subtype: 'NON_OPERATING', isHeader: true, parent: '8100' },
  { code: '8110.01', name: 'Biaya Pajak Non Operasional', type: 'EXPENSE', subtype: 'NON_OPERATING', cashflow: 'OPERATING', parent: '8110' },
  { code: '8110.02', name: 'Bank Charge Expense', type: 'EXPENSE', subtype: 'NON_OPERATING', cashflow: 'OPERATING', parent: '8110' },
];
